# Introduction to Datamining
#### Instructor : Zia Beheshti, School of Engineering, [Azad U, South Tehran Branch](http://www/azad/ac/ir)

# Numpy cheatsheet

In [2]:
!pip install numpy

In [3]:
import numpy as np

## Creating arrays

Creating arrays

In [4]:
# Creating arrays
a = np.array([1,2,3,8]) # one-dimentional array
b = np.array([(1,2,3),(4,5,6),(7,8,9)]) # two-dimenttional array
print('a is : ', a)
print('b is :\n', b)

a is :  [1 2 3 8]
b is :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Elements access

In [5]:
print(b[1,1]) # element wise access

print(b[:2,:]) # range wise access

print(b[-1, 1:3])

c = np.arange(2,20,3) #create in range
print(c)

5
[[1 2 3]
 [4 5 6]]
[8 9]
[ 2  5  8 11 14 17]


Boolean Indexing

In [6]:
a = np.array([8,3,1,4,6,2,9,0,-7,14])
print(a[a<7]) # boolean indexing
print(a.any())
print(a.all())
b = a[[1,2,0,0]] # fancy indexing
print(b)

idx = [3,1,2] # another type of fancy indexing
print(a[idx])


[ 3  1  4  6  2  0 -7]
True
False
[3 1 8 8]
[4 3 1]


Create range arrays

In [7]:
c = np.arange(100,8,-12) #create in range
print(c)
zlist = np.zeros((3,5), dtype = np.int16) #create 3-by-5 zero matrix
print(zlist)
oneList = np.ones((2,2))
print(oneList)

x = np.linspace(0,2,9)
print(x)

y = np.eye(3)
print(y)

z= np.random.random((3,4))
print(z)

t = np.full((3,4),1.5)
print(t)

print(len(c))
print(len(zlist))
print(len(zlist[1,:]))
print(np.shape(zlist))

[100  88  76  64  52  40  28  16]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1. 1.]
 [1. 1.]]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.21765099 0.86398751 0.0228019  0.33063225]
 [0.42402266 0.65492502 0.53413781 0.72308263]
 [0.46951365 0.35336722 0.14481037 0.23547286]]
[[1.5 1.5 1.5 1.5]
 [1.5 1.5 1.5 1.5]
 [1.5 1.5 1.5 1.5]]
8
3
5
(3, 5)


## <b> <font color = 'red'> Arithmetic operation</font></b>

In [8]:
g = a + a
print (g)
g = np.add(a,a)
print(g)

m1 = np.array([(1,2),(3,4)])
m2 = np.array([(5,6),(7,8)])

# element wise multiplication
m3 = m1 * m2
print(m3)

m3 = np.multiply(m1,m2)
print(m3)

# Matrix dot product
m3 = np.dot(m1,m2)
print(m3)

#other math function
m3 = np.exp(m1)
print(m3)

m3 = np.sin(m1) # also np.log , np.cos , np.sqrt
print(m3)




[ 16   6   2   8  12   4  18   0 -14  28]
[ 16   6   2   8  12   4  18   0 -14  28]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]


## <b> <font color = 'red'> Comparison</font></b>

In [9]:
print (m1==m2)
print(m1 < m2)
print(m1 + 5 > m2)
print(np.array_equal(m1 ,m2))
print(np.array_equal(m1 ,m1))
m3 = m1 # reference copy
print(np.array_equal(m3 ,m1))
m3[1,1] = 100
print(np.array_equal(m3 ,m1))
print(m1)


[[False False]
 [False False]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
False
True
True
True
[[  1   2]
 [  3 100]]


## <b> <font color = 'green'> Argregate functions</font></b>

In [10]:
print(' sum of elements : ', m1.sum())
print(' minimum of elements : ', m1.min())
print(' minimum of elements in columns: ', m1.min(axis=0))
print(' minimum of elements in rows: ', m1.min(axis=1))
print(' cummulative sum: ', m1.cumsum(axis=1))
print(' cummulative sum: ', np.cumsum(m1, axis=1))

print(' average : ', m1.mean())
print(c)
print(' median : ', np.median(c))

print(' standard deviation: ', c.std())
print(' standard deviation: ', np.std(c))

print(' correlation coefficent: ', np.corrcoef(c))

print(' correlation coefficent: ', np.corrcoef(m1))




 sum of elements :  106
 minimum of elements :  1
 minimum of elements in columns:  [1 2]
 minimum of elements in rows:  [1 3]
 cummulative sum:  [[  1   3]
 [  3 103]]
 cummulative sum:  [[  1   3]
 [  3 103]]
 average :  26.5
[100  88  76  64  52  40  28  16]
 median :  58.0
 standard deviation:  27.49545416973504
 standard deviation:  27.49545416973504
 correlation coefficent:  1.0
 correlation coefficent:  [[1. 1.]
 [1. 1.]]


Copying Arrays

In [11]:
m1_copy = m1.copy() # Create a deep copy of array
m1_copy

array([[  1,   2],
       [  3, 100]])

Sorting Arrays

In [12]:
mat = np.array([(5,3,1,7),(9,2,1,8)])
print('original matrix\n', mat)
mat.sort()
print('sorted matrix\n' , mat) # sort each row independently

mat = np.array([(5,3,1,7),(9,2,1,8)])
mat.sort(axis = 0)
print('sorted matrix\n' , mat) # sort each column independently


original matrix
 [[5 3 1 7]
 [9 2 1 8]]
sorted matrix
 [[1 3 5 7]
 [1 2 8 9]]
sorted matrix
 [[5 2 1 7]
 [9 3 1 8]]


In [13]:
c = np.array([5,2,8,2,4])    
a = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14],
              [15, 16, 17, 18, 19],
              [20, 21, 22, 23, 24]])

i = np.argsort(c)
print(i)
a = a[:,i]
print(a)

[1 3 4 0 2]
[[ 1  3  4  0  2]
 [ 6  8  9  5  7]
 [11 13 14 10 12]
 [16 18 19 15 17]
 [21 23 24 20 22]]


## Array Manipulation

Transposing Array

In [14]:
b = a.transpose()
print(b)

[[ 1  6 11 16 21]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 0  5 10 15 20]
 [ 2  7 12 17 22]]


Changing Array shape

In [15]:
a = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
print('Shape of a is ' ,a.shape)
b =a.ravel()
print('Shape of b is ' ,b.shape)
print(b)
print(a)

Shape of a is  (3, 5)
Shape of b is  (15,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [16]:
b.reshape((5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Adding / Removing Elements

In [22]:
d = np.resize(a,(4,5))
print(d)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [ 0  1  2  3  4]]


Append items to an array

In [38]:
a = np.array([[1,2,3],
     [4,5,6]])
b = np.array([[10,20,30],[40,50,60]])
c = np.append(a,b, axis =0)
print(c)

d = np.append(a,b, axis =1)
print(d)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]


Insert Items in an array

In [52]:
a = np.array([[1,2,3,4]])
b = np.array([5,6])
c = np.insert(a,1,b)
print(c)


[1 5 6 2 3 4]


delete items

In [53]:
c = np.delete(c,[1,3])
print(c)

[1 6 3 4]


Concatenating Arrays

In [56]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[10,20,30,40],[50,60,70,80]])
c = np.concatenate((a,b), axis = 0)
print(c)

d = np.vstack((a,b))
print(d)

e = np.hstack((a,b))
print(e)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]
[[ 1  2  3  4 10 20 30 40]
 [ 5  6  7  8 50 60 70 80]]


Splitting Arrays

In [59]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.hsplit(a, 2)
print(b)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


## Save and Load

In [ ]:
np.save('myArray' ,a)
a = np.load('myArray)')
np.genfromtest("my_file.csv" , delimeter = ',')
np.savetext("myarray", a, delimeter = "|")